//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kino
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILM
    {
        public FILM()
        {
            this.POKUPKA_BILETA = new HashSet<POKUPKA_BILETA>();
        }
    
        public int Id_film { get; set; }
        public string name_film { get; set; }
        public string zanr { get; set; }
        public Nullable<double> reiting { get; set; }
        public Nullable<int> time_film { get; set; }
        public string reziser { get; set; }
        public string opisaniey_film { get; set; }
        public Nullable<int> year_vipuska { get; set; }
        public string photo { get; set; }
    
        public virtual ICollection<POKUPKA_BILETA> POKUPKA_BILETA { get; set; }
    }
}
