//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kino
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FILM> FILM { get; set; }
        public DbSet<POKUPKA_BILETA> POKUPKA_BILETA { get; set; }
        public DbSet<USER> USER { get; set; }
        public DbSet<USER_HISTIRY> USER_HISTIRY { get; set; }
        public DbSet<ZAL> ZAL { get; set; }
    }
}
