//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kino
{
    using System;
    using System.Collections.Generic;
    
    public partial class POKUPKA_BILETA
    {
        public int Id_bilet { get; set; }
        public Nullable<System.DateTime> data_time_pokup { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> Id_film { get; set; }
        public Nullable<int> Id_zal { get; set; }
        public Nullable<int> Id_user { get; set; }
        public Nullable<int> mesto { get; set; }
    
        public virtual FILM FILM { get; set; }
        public virtual ZAL ZAL { get; set; }
        public virtual USER USER { get; set; }
    }
}
