//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kino
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_HISTIRY
    {
        public int Id_histiry { get; set; }
        public Nullable<System.DateTime> time_VHOD { get; set; }
        public Nullable<System.DateTime> time_VIHOD { get; set; }
        public Nullable<int> Id_user { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
