//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kino
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZAL
    {
        public ZAL()
        {
            this.POKUPKA_BILETA = new HashSet<POKUPKA_BILETA>();
        }
    
        public int Id_zal { get; set; }
        public Nullable<int> kolvo_mest { get; set; }
        public string tip_zal { get; set; }
    
        public virtual ICollection<POKUPKA_BILETA> POKUPKA_BILETA { get; set; }
    }
}
